-- STORED PROCEDURE TO INSERT DATA INTO TABLE

-- DEPARTMENT TABLE
CREATE PROC SP_DEPARTMENT_INSERT
    @DEPT_NAME NVARCHAR(100)
AS
BEGIN
    INSERT INTO DEPARTMENT
        (DEPT_NAME)
    VALUES
        (@DEPT_NAME);
END

-- PRODUCT TABLE
CREATE PROC SP_PRODUCTS_INSERT
    @PRODUCTNAME NVARCHAR(100),
    @SUPPLIERID INT,
    @CATEGORYID INT,
    @QUANTITYPERUNIT NVARCHAR(50),
    @UNITPRICE DECIMAL(10,2),
    @UNITSINSTOCK INT,
    @UNITSONORDER INT,
    @REORDERLEVEL INT,
    @DISCONTINUED BIT
AS
BEGIN
    INSERT INTO PRODUCTS
        (PRODUCTNAME
        SUPPLIERID,
        CATEGORYID,
        QUANTITYPERUNIT,
        UNITPRICE,
        UNITSINSTOCK,
        UNITSONORDER,
        REORDERLEVEL,
        DISCONTINUED
        )
        VALUES
    (@PRODUCTNAME,@SUPPLIERID,@CATEGORYID,@QUANTITYPERUNIT,@UNITPRICE,@UNITSINSTOCK,@UNITSONORDER,@REORDERLEVEL,@DISCONTINUED)
END

-- STORED PROCEDURE TO UPDATE DATA INTO DEPARTMENT TABLE

CREATE PROC SP_DEPARTMENT_UPDATE
    @DEPT_ID INT,
    @DEPT_NAME NVARCHAR(100)
AS
BEGIN
    UPDATE DEPARTMENT
    SET DEPT_NAME=@DEPT_NAME
    WHERE DEPT_ID=@DEPT_ID
END

