SELECT * FROM DEMOCATEGORIES
SELECT * FROM DEMOCUSTOMERS
SELECT * FROM DemoEmployees
SELECT * FROM DEMOORDERDETAILS
SELECT * FROM DEMOORDERS
SELECT * FROM DEMOPRODUCTS

-- 1.Create a stored procedure in the Northwind database that will calculate the average value of Freight for a specified customer.
-- Then, a business rule will be added that will be triggered before every Update and Insert command in the Orders controller,
-- and will use the stored procedure to verify that the Freight does not exceed the average freight.
-- If it does, a message will be displayed and the command will be cancelled.

GO
CREATE PROC PR_CALCULATEAVGFREIGHT_T17
    @CUSTOMERID nchar(5),
    @AVGFRIEGHT DECIMAL(19,2) OUTPUT
AS
BEGIN  
    SELECT @AVGFRIEGHT=AVG(FREIGHT)
    FROM DEMOOORDERS
    WHERE CUSTOMERID=@CUSTOMERID
END

GO
CREATE TRIGGER before_insert_trigger
ON DEMOORDERS
AFTER INSERT, UPDATE
AS 
BEGIN
    DECLARE @FREIGHT DECIMAL(19,2)
    DECLARE @CUSTOMERID NCHAR(5)
    SELECT @FREIGHT=FREIGHT,@CUSTOMERID=CUSTOMERID FROM DEMOORDERS
    PRINT @FREIGHT
    PRINT @CUSTOMERID

    DECLARE @AVGFRIEGHT DECIMAL(19,2)
    EXEC PR_CALCULATEAVGFREIGHT @CUSTOMERID,@AVGFRIEGHT OUTPUT

    IF @FREIGHT>@AVGFRIEGHT
    BEGIN
        DELETE FROM DEMOORDERS WHERE CUSTOMERID=@CUSTOMERID
    END
END

SELECT AVG(FREIGHT) FROM DEMOORDERS


-- 2. write a SQL query to Create Stored procedure in the Northwind database
-- to retrieve Employee Sales by Country

GO
CREATE PROCEDURE PR_SALESBYCOUNTRY
AS
BEGIN
    SELECT E.COUNTRY,SUM(OD.UNITPRICE*OD.QUANTITY) AS SALES
    from DemoEmployees E JOIN DEMOORDERS O ON E.EMPLOYEEID=O.EMPLOYEEID
    JOIN DEMOORDERDETAILS OD ON O.ORDERID=OD.ORDERID
    GROUP BY E.COUNTRY
END
GO;

-- 3. write a SQL query to Create Stored procedure in the Northwind database
-- to retrieve Sales by Year
CREATE PROC PR_SALESBYYEAR
AS
BEGIN
    SELECT YEAR(O.ORDERDATE) AS YEAROFORDER, SUM(OD.UNITPRICE*OD.QUANTITY) AS SALES
    FROM DEMOORDERS O JOIN DEMOORDERDETAILS OD ON O.ORDERID=OD.ORDERID
    GROUP BY YEAR(O.ORDERDATE)
END

-- 4. write a SQL query to Create Stored procedure in the Northwind database
-- to retrieve Sales By Category
SELECT * FROM DEMOORDERS
SELECT * FROM DEMOPRODUCTS
SELECT * FROM DEMOCUSTOMERS
SELECT * FROM DEMOORDERDETAILS

GO
CREATE PROC PR_SALESBYCATEGORY
AS
BEGIN
    SELECT c.categoryname,SUM(O.UNITPRICE*O.QUANTITY) as Sales
    FROM DEMOORDERDETAILS O JOIN DEMOPRODUCTS P ON O.PRODUCTID=P.PRODUCTID
    join DemoCategories c on p.categoryid=c.categoryid
    GROUP by c.categoryname
END
GO;


-- 5. write a SQL query to Create Stored procedure in the Northwind database
-- to retrieve Ten Most Expensive Products

CREATE PROC PR_PRODUCTS_TOP10EXPENSIVEPRODUCT
AS
BEGIN
    SELECT TOP 10 *
    FROM DEMOPRODUCTS
    ORDER BY UNITPRICE DESC
END

-- 6 .write a SQL query to Create Stored procedure in the Northwind database
-- to insert Customer Order Details

GO
CREATE PROC PR_CUSTOMERORDER_INSERT_T17
    @CUSTOMERID NCHAR(5),
    @EMPLOYEEID INT,
    @ORDERDATE DATETIME,
    @REQUIREDDATE DATETIME,
    @SHIPPEDDATE DATETIME,
    @SHIPVIA INT,
    @FREIGHT DECIMAL(19,2),
    @SHIPNAME NVARCHAR(40),
    @SHIPADDRESS NVARCHAR(60),
    @SHIPCITY NVARCHAR(15),
    @SHIPREGION NVARCHAR(15),
    @SHIPPOSTALCODE NVARCHAR(10),
    @SHIPCOUNTRY NVARCHAR(15)
AS
BEGIN
    INSERT INTO DEMOORDERS
    (CUSTOMERID,EMPLOYEEID,ORDERDATE,REQUIREDDATE,SHIPPEDDATE,
    SHIPVIA,FREIGHT,SHIPNAME,SHIPADDRESS,SHIPCITY,SHIPREGION,SHIPPOSTALCODE,SHIPCOUNTRY)
    VALUES
    (@CUSTOMERID,@EMPLOYEEID,@ORDERDATE,@REQUIREDDATE,@SHIPPEDDATE,
    @SHIPVIA,@FREIGHT,@SHIPNAME,@SHIPADDRESS,@SHIPCITY,@SHIPREGION,@SHIPPOSTALCODE,@SHIPCOUNTRY)
END

-- 7. write a SQL query to Create Stored procedure in the Northwind database
-- to update Customer Order Details

GO
CREATE PROC PR_CUSTOMERORDER_UPDATE
    @ORDERID INT,
    @CUSTOMERID NCHAR(5),
    @EMPLOYEEID INT,
    @ORDERDATE DATETIME,
    @REQUIREDDATE DATETIME,
    @SHIPPEDDATE DATETIME,
    @SHIPVIA INT,
    @FREIGHT DECIMAL(19,2),
    @SHIPNAME NVARCHAR(40),
    @SHIPADDRESS NVARCHAR(60),
    @SHIPCITY NVARCHAR(15),
    @SHIPREGION NVARCHAR(15),
    @SHIPPOSTALCODE NVARCHAR(10),
    @SHIPCOUNTRY NVARCHAR(15)
AS
BEGIN
    UPDATE DEMOORDERS
    SET
    CUSTOMERID=@CUSTOMERID,
    EMPLOYEEID=@EMPLOYEEID,
    ORDERDATE=@ORDERDATE,
    REQUIREDDATE=@REQUIREDDATE,
    SHIPPEDDATE=@SHIPPEDDATE,
    SHIPVIA=@SHIPVIA,
    FREIGHT=@FREIGHT,
    SHIPNAME=@SHIPNAME,
    SHIPADDRESS=@SHIPADDRESS,
    SHIPCITY=@SHIPCITY,
    SHIPREGION=@SHIPREGION,
    SHIPPOSTALCODE=@SHIPPOSTALCODE,
    SHIPCOUNTRY=@SHIPCOUNTRY
    WHERE ORDERID=@ORDERID
END


-- STORED PROCEDURE TO INSERT DATA INTO TABLE

-- DEPARTMENT TABLE
GO
CREATE PROC SP_DEPARTMENT_INSERT
    @DEPT_NAME NVARCHAR(100)
AS
BEGIN
    INSERT INTO DEPARTMENT
        (DEPT_NAME)
    VALUES
        (@DEPT_NAME);
END

-- PRODUCT TABLE

GO
CREATE PROC SP_PRODUCTS_INSERT
    @PRODUCTNAME NVARCHAR(100),
    @SUPPLIERID INT,
    @CATEGORYID INT,
    @QUANTITYPERUNIT NVARCHAR(50),
    @UNITPRICE DECIMAL(10,2),
    @UNITSINSTOCK INT,
    @UNITSONORDER INT,
    @REORDERLEVEL INT,
    @DISCONTINUED BIT
AS
BEGIN
    INSERT INTO PRODUCTS
        (PRODUCTNAME,
        SUPPLIERID,
        CATEGORYID,
        QUANTITYPERUNIT,
        UNITPRICE,
        UNITSINSTOCK,
        UNITSONORDER,
        REORDERLEVEL,
        DISCONTINUED
        )
        VALUES
    (@PRODUCTNAME,@SUPPLIERID,@CATEGORYID,@QUANTITYPERUNIT,@UNITPRICE,@UNITSINSTOCK,@UNITSONORDER,@REORDERLEVEL,@DISCONTINUED)
END

-- STORED PROCEDURE TO UPDATE DATA INTO DEPARTMENT TABLE

GO
CREATE PROC SP_DEPARTMENT_UPDATE
    @DEPT_ID INT,
    @DEPT_NAME NVARCHAR(100)
AS
BEGIN
    UPDATE DEPARTMENT
    SET DEPT_NAME=@DEPT_NAME
    WHERE DEPT_ID=@DEPT_ID
END











